"""Add service_name to User model

Revision ID: 1e7866a56df5
Revises: b16ad8d80f47
Create Date: 2024-11-01 02:05:22.675837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7866a56df5'
down_revision = 'b16ad8d80f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('service_name')

    # ### end Alembic commands ###
