"""Add experience to User model

Revision ID: 58173775e6ad
Revises: 1e7866a56df5
Create Date: 2024-11-01 02:11:35.790288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58173775e6ad'
down_revision = '1e7866a56df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
