"""Add pin_code to User model

Revision ID: b16ad8d80f47
Revises: c2130ad887d0
Create Date: 2024-10-31 13:49:57.800950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16ad8d80f47'
down_revision = 'c2130ad887d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pin_code')

    # ### end Alembic commands ###
